version: '3.8'

services:
  wordpress:
    image: wordpress
    restart : always
    environment:
      - WORDPRESS_DB_USER=wpuser
      - WORDPRESS_DB_PASSWORD=wpuser@
      - WORDPRESS_DB_NAME=wordpress_db
      - WORDPRESS_DB_HOST=db:3306
    volumes:
      - /root/wordpress/html:/var/www/html
    ports:
      - "8081:80"
    depends_on:
      - db

  db:
    container_name: wordpressdb
    image: mariadb
    restart : always
    environment:
      - MYSQL_ROOT_PASSWORD=asd123
      - MYSQL_USER=wpuser
      - MYSQL_PASSWORD=wpuser@
      - MYSQL_DATABASE=wordpress_db
    volumes:
      - /root/wordpress/database:/var/lib/mysql
  